### ISSUE TITLE
Need to Track Conversation Duplicates

### ISSUE THREAD

**Issue by davidpmontes** [davidpmontes/json-twitter#1]
For example, I have processed 10 conversations so far and now I am processing number 11 but I see that it shares a tweet in common with number 2.  So instead of creating conversation 11, I add all the tweets from the "halted" 11 to number 2.  Now I continue with the next conversation which is still number 11.  So if conversation 2 was created from folder 525xxxxxxxxxxxxx and conversation 11 was attempting to be created from folder 525yyyyyyyyyyyy, then I could just write to a "merged" file that "525yyyyyyyyyyy merged with 525xxxxxxxxxxxxx".  What if later on, folder 525zzzzzzzzzzzzzz also matched 525xxxxxxxxxxxx?  Would you want that merge to just be recorded as "525zzzzzzzzzzz merged with 525xxxxxxxxxxxx".  Or should the script consolodate documenting the merges like "525xxxxxxxxxxxx 525yyyyyyyyyyyy 525zzzzzzzzzzzzz".

**Comment by teresagl** [comment]
It would be better to document that mergers completely; so, "525xxxxxxxxxxxx 525yyyyyyyyyyyy 525zzzzzzzzzzzzz" better than "525zzzzzzzzzzz merged with 525xxxxxxxxxxxx". That would allow to track the entire conversation and go back to check the corresponding folders if necessary.

**Comment by davidpmontes** [comment]
The program now creates a merges.csv.  The first column is the original folder and the subsequent columns are the folders that were merged with the first.
